
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ContainmentBtnsAddBtn': typeof import("../components/Containment/Btns/AddBtn.vue")['default']
    'ContainmentBtnsBackBtn': typeof import("../components/Containment/Btns/BackBtn.vue")['default']
    'ContainmentBtnsCloseBtn': typeof import("../components/Containment/Btns/CloseBtn.vue")['default']
    'ContainmentBtnsExpandBtn': typeof import("../components/Containment/Btns/ExpandBtn.vue")['default']
    'ContainmentBtnsLanguageChangeBtn': typeof import("../components/Containment/Btns/LanguageChangeBtn.vue")['default']
    'ContainmentBtnsNavBtns': typeof import("../components/Containment/Btns/NavBtns.vue")['default']
    'ContainmentBtnsScrollTopBtn': typeof import("../components/Containment/Btns/ScrollTopBtn.vue")['default']
    'ContainmentBtnsSubmitBtn': typeof import("../components/Containment/Btns/SubmitBtn.vue")['default']
    'ContainmentBtnsToggleThemeBtn': typeof import("../components/Containment/Btns/ToggleThemeBtn.vue")['default']
    'ContainmentCardsDetailCard': typeof import("../components/Containment/Cards/DetailCard.vue")['default']
    'ContainmentImgBaseImg': typeof import("../components/Containment/Img/BaseImg.vue")['default']
    'ContainmentImgPlaceholder': typeof import("../components/Containment/Img/ImgPlaceholder.vue")['default']
    'DialogsBaseDialog': typeof import("../components/Dialogs/BaseDialog.vue")['default']
    'DialogsConfirmDialog': typeof import("../components/Dialogs/ConfirmDialog.vue")['default']
    'FilmSubComponentsFilmAssessments': typeof import("../components/FilmSubComponents/FilmAssessments.vue")['default']
    'FilmSubComponentsFilmDetailMenu': typeof import("../components/FilmSubComponents/FilmDetailMenu.vue")['default']
    'FilmSubComponentsFilmDrawerContent': typeof import("../components/FilmSubComponents/FilmDrawerContent.vue")['default']
    'FormsAssessmentForm': typeof import("../components/Forms/AssessmentForm.vue")['default']
    'FormsFilmForm': typeof import("../components/Forms/FilmForm.vue")['default']
    'FormsPersonForm': typeof import("../components/Forms/PersonForm.vue")['default']
    'FormsUserForm': typeof import("../components/Forms/UserForm.vue")['default']
    'GalleryFilmGalleryEdit': typeof import("../components/Gallery/FilmGalleryEdit.vue")['default']
    'GalleryFullscreenViewer': typeof import("../components/Gallery/GalleryFullscreenViewer.vue")['default']
    'GalleryUploader': typeof import("../components/Gallery/GalleryUploader.vue")['default']
    'GalleryViewer': typeof import("../components/Gallery/GalleryViewer.vue")['default']
    'GalleryPartialsMultipleImgSelector': typeof import("../components/Gallery/Partials/MultipleImgSelector.vue")['default']
    'GalleryPartialsSingleImgSelector': typeof import("../components/Gallery/Partials/SingleImgSelector.vue")['default']
    'GalleryPersonGalleryEdit': typeof import("../components/Gallery/PersonGalleryEdit.vue")['default']
    'MiscBaseError': typeof import("../components/Misc/BaseError.vue")['default']
    'MiscCardLoader': typeof import("../components/Misc/CardLoader.vue")['default']
    'MiscFileUploader': typeof import("../components/Misc/FileUploader.vue")['default']
    'MiscFilters': typeof import("../components/Misc/Filters.vue")['default']
    'MiscIndentedEditableText': typeof import("../components/Misc/IndentedEditableText.vue")['default']
    'MiscListPage': typeof import("../components/Misc/ListPage.vue")['default']
    'MiscLoadingScreen': typeof import("../components/Misc/LoadingScreen.vue")['default']
    'MiscLogo': typeof import("../components/Misc/Logo.vue")['default']
    'MiscNotAuthWarning': typeof import("../components/Misc/NotAuthWarning.vue")['default']
    'MiscSearch': typeof import("../components/Misc/Search.vue")['default']
    'MiscSuccessSnackbar': typeof import("../components/Misc/SuccessSnackbar.vue")['default']
    'NavigationAppNavDrawerContent': typeof import("../components/Navigation/AppNavDrawerContent.vue")['default']
    'NavigationProfileNav': typeof import("../components/Navigation/ProfileNav.vue")['default']
    'AuthState': typeof import("../node_modules/.pnpm/nuxt-auth-utils@0.5.14_@simplewebauthn+browser@13.1.0_@simplewebauthn+server@13.1.1_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyContainmentBtnsAddBtn': typeof import("../components/Containment/Btns/AddBtn.vue")['default']
    'LazyContainmentBtnsBackBtn': typeof import("../components/Containment/Btns/BackBtn.vue")['default']
    'LazyContainmentBtnsCloseBtn': typeof import("../components/Containment/Btns/CloseBtn.vue")['default']
    'LazyContainmentBtnsExpandBtn': typeof import("../components/Containment/Btns/ExpandBtn.vue")['default']
    'LazyContainmentBtnsLanguageChangeBtn': typeof import("../components/Containment/Btns/LanguageChangeBtn.vue")['default']
    'LazyContainmentBtnsNavBtns': typeof import("../components/Containment/Btns/NavBtns.vue")['default']
    'LazyContainmentBtnsScrollTopBtn': typeof import("../components/Containment/Btns/ScrollTopBtn.vue")['default']
    'LazyContainmentBtnsSubmitBtn': typeof import("../components/Containment/Btns/SubmitBtn.vue")['default']
    'LazyContainmentBtnsToggleThemeBtn': typeof import("../components/Containment/Btns/ToggleThemeBtn.vue")['default']
    'LazyContainmentCardsDetailCard': typeof import("../components/Containment/Cards/DetailCard.vue")['default']
    'LazyContainmentImgBaseImg': typeof import("../components/Containment/Img/BaseImg.vue")['default']
    'LazyContainmentImgPlaceholder': typeof import("../components/Containment/Img/ImgPlaceholder.vue")['default']
    'LazyDialogsBaseDialog': typeof import("../components/Dialogs/BaseDialog.vue")['default']
    'LazyDialogsConfirmDialog': typeof import("../components/Dialogs/ConfirmDialog.vue")['default']
    'LazyFilmSubComponentsFilmAssessments': typeof import("../components/FilmSubComponents/FilmAssessments.vue")['default']
    'LazyFilmSubComponentsFilmDetailMenu': typeof import("../components/FilmSubComponents/FilmDetailMenu.vue")['default']
    'LazyFilmSubComponentsFilmDrawerContent': typeof import("../components/FilmSubComponents/FilmDrawerContent.vue")['default']
    'LazyFormsAssessmentForm': typeof import("../components/Forms/AssessmentForm.vue")['default']
    'LazyFormsFilmForm': typeof import("../components/Forms/FilmForm.vue")['default']
    'LazyFormsPersonForm': typeof import("../components/Forms/PersonForm.vue")['default']
    'LazyFormsUserForm': typeof import("../components/Forms/UserForm.vue")['default']
    'LazyGalleryFilmGalleryEdit': typeof import("../components/Gallery/FilmGalleryEdit.vue")['default']
    'LazyGalleryFullscreenViewer': typeof import("../components/Gallery/GalleryFullscreenViewer.vue")['default']
    'LazyGalleryUploader': typeof import("../components/Gallery/GalleryUploader.vue")['default']
    'LazyGalleryViewer': typeof import("../components/Gallery/GalleryViewer.vue")['default']
    'LazyGalleryPartialsMultipleImgSelector': typeof import("../components/Gallery/Partials/MultipleImgSelector.vue")['default']
    'LazyGalleryPartialsSingleImgSelector': typeof import("../components/Gallery/Partials/SingleImgSelector.vue")['default']
    'LazyGalleryPersonGalleryEdit': typeof import("../components/Gallery/PersonGalleryEdit.vue")['default']
    'LazyMiscBaseError': typeof import("../components/Misc/BaseError.vue")['default']
    'LazyMiscCardLoader': typeof import("../components/Misc/CardLoader.vue")['default']
    'LazyMiscFileUploader': typeof import("../components/Misc/FileUploader.vue")['default']
    'LazyMiscFilters': typeof import("../components/Misc/Filters.vue")['default']
    'LazyMiscIndentedEditableText': typeof import("../components/Misc/IndentedEditableText.vue")['default']
    'LazyMiscListPage': typeof import("../components/Misc/ListPage.vue")['default']
    'LazyMiscLoadingScreen': typeof import("../components/Misc/LoadingScreen.vue")['default']
    'LazyMiscLogo': typeof import("../components/Misc/Logo.vue")['default']
    'LazyMiscNotAuthWarning': typeof import("../components/Misc/NotAuthWarning.vue")['default']
    'LazyMiscSearch': typeof import("../components/Misc/Search.vue")['default']
    'LazyMiscSuccessSnackbar': typeof import("../components/Misc/SuccessSnackbar.vue")['default']
    'LazyNavigationAppNavDrawerContent': typeof import("../components/Navigation/AppNavDrawerContent.vue")['default']
    'LazyNavigationProfileNav': typeof import("../components/Navigation/ProfileNav.vue")['default']
    'LazyAuthState': typeof import("../node_modules/.pnpm/nuxt-auth-utils@0.5.14_@simplewebauthn+browser@13.1.0_@simplewebauthn+server@13.1.1_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ContainmentBtnsAddBtn: typeof import("../components/Containment/Btns/AddBtn.vue")['default']
export const ContainmentBtnsBackBtn: typeof import("../components/Containment/Btns/BackBtn.vue")['default']
export const ContainmentBtnsCloseBtn: typeof import("../components/Containment/Btns/CloseBtn.vue")['default']
export const ContainmentBtnsExpandBtn: typeof import("../components/Containment/Btns/ExpandBtn.vue")['default']
export const ContainmentBtnsLanguageChangeBtn: typeof import("../components/Containment/Btns/LanguageChangeBtn.vue")['default']
export const ContainmentBtnsNavBtns: typeof import("../components/Containment/Btns/NavBtns.vue")['default']
export const ContainmentBtnsScrollTopBtn: typeof import("../components/Containment/Btns/ScrollTopBtn.vue")['default']
export const ContainmentBtnsSubmitBtn: typeof import("../components/Containment/Btns/SubmitBtn.vue")['default']
export const ContainmentBtnsToggleThemeBtn: typeof import("../components/Containment/Btns/ToggleThemeBtn.vue")['default']
export const ContainmentCardsDetailCard: typeof import("../components/Containment/Cards/DetailCard.vue")['default']
export const ContainmentImgBaseImg: typeof import("../components/Containment/Img/BaseImg.vue")['default']
export const ContainmentImgPlaceholder: typeof import("../components/Containment/Img/ImgPlaceholder.vue")['default']
export const DialogsBaseDialog: typeof import("../components/Dialogs/BaseDialog.vue")['default']
export const DialogsConfirmDialog: typeof import("../components/Dialogs/ConfirmDialog.vue")['default']
export const FilmSubComponentsFilmAssessments: typeof import("../components/FilmSubComponents/FilmAssessments.vue")['default']
export const FilmSubComponentsFilmDetailMenu: typeof import("../components/FilmSubComponents/FilmDetailMenu.vue")['default']
export const FilmSubComponentsFilmDrawerContent: typeof import("../components/FilmSubComponents/FilmDrawerContent.vue")['default']
export const FormsAssessmentForm: typeof import("../components/Forms/AssessmentForm.vue")['default']
export const FormsFilmForm: typeof import("../components/Forms/FilmForm.vue")['default']
export const FormsPersonForm: typeof import("../components/Forms/PersonForm.vue")['default']
export const FormsUserForm: typeof import("../components/Forms/UserForm.vue")['default']
export const GalleryFilmGalleryEdit: typeof import("../components/Gallery/FilmGalleryEdit.vue")['default']
export const GalleryFullscreenViewer: typeof import("../components/Gallery/GalleryFullscreenViewer.vue")['default']
export const GalleryUploader: typeof import("../components/Gallery/GalleryUploader.vue")['default']
export const GalleryViewer: typeof import("../components/Gallery/GalleryViewer.vue")['default']
export const GalleryPartialsMultipleImgSelector: typeof import("../components/Gallery/Partials/MultipleImgSelector.vue")['default']
export const GalleryPartialsSingleImgSelector: typeof import("../components/Gallery/Partials/SingleImgSelector.vue")['default']
export const GalleryPersonGalleryEdit: typeof import("../components/Gallery/PersonGalleryEdit.vue")['default']
export const MiscBaseError: typeof import("../components/Misc/BaseError.vue")['default']
export const MiscCardLoader: typeof import("../components/Misc/CardLoader.vue")['default']
export const MiscFileUploader: typeof import("../components/Misc/FileUploader.vue")['default']
export const MiscFilters: typeof import("../components/Misc/Filters.vue")['default']
export const MiscIndentedEditableText: typeof import("../components/Misc/IndentedEditableText.vue")['default']
export const MiscListPage: typeof import("../components/Misc/ListPage.vue")['default']
export const MiscLoadingScreen: typeof import("../components/Misc/LoadingScreen.vue")['default']
export const MiscLogo: typeof import("../components/Misc/Logo.vue")['default']
export const MiscNotAuthWarning: typeof import("../components/Misc/NotAuthWarning.vue")['default']
export const MiscSearch: typeof import("../components/Misc/Search.vue")['default']
export const MiscSuccessSnackbar: typeof import("../components/Misc/SuccessSnackbar.vue")['default']
export const NavigationAppNavDrawerContent: typeof import("../components/Navigation/AppNavDrawerContent.vue")['default']
export const NavigationProfileNav: typeof import("../components/Navigation/ProfileNav.vue")['default']
export const AuthState: typeof import("../node_modules/.pnpm/nuxt-auth-utils@0.5.14_@simplewebauthn+browser@13.1.0_@simplewebauthn+server@13.1.1_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyContainmentBtnsAddBtn: typeof import("../components/Containment/Btns/AddBtn.vue")['default']
export const LazyContainmentBtnsBackBtn: typeof import("../components/Containment/Btns/BackBtn.vue")['default']
export const LazyContainmentBtnsCloseBtn: typeof import("../components/Containment/Btns/CloseBtn.vue")['default']
export const LazyContainmentBtnsExpandBtn: typeof import("../components/Containment/Btns/ExpandBtn.vue")['default']
export const LazyContainmentBtnsLanguageChangeBtn: typeof import("../components/Containment/Btns/LanguageChangeBtn.vue")['default']
export const LazyContainmentBtnsNavBtns: typeof import("../components/Containment/Btns/NavBtns.vue")['default']
export const LazyContainmentBtnsScrollTopBtn: typeof import("../components/Containment/Btns/ScrollTopBtn.vue")['default']
export const LazyContainmentBtnsSubmitBtn: typeof import("../components/Containment/Btns/SubmitBtn.vue")['default']
export const LazyContainmentBtnsToggleThemeBtn: typeof import("../components/Containment/Btns/ToggleThemeBtn.vue")['default']
export const LazyContainmentCardsDetailCard: typeof import("../components/Containment/Cards/DetailCard.vue")['default']
export const LazyContainmentImgBaseImg: typeof import("../components/Containment/Img/BaseImg.vue")['default']
export const LazyContainmentImgPlaceholder: typeof import("../components/Containment/Img/ImgPlaceholder.vue")['default']
export const LazyDialogsBaseDialog: typeof import("../components/Dialogs/BaseDialog.vue")['default']
export const LazyDialogsConfirmDialog: typeof import("../components/Dialogs/ConfirmDialog.vue")['default']
export const LazyFilmSubComponentsFilmAssessments: typeof import("../components/FilmSubComponents/FilmAssessments.vue")['default']
export const LazyFilmSubComponentsFilmDetailMenu: typeof import("../components/FilmSubComponents/FilmDetailMenu.vue")['default']
export const LazyFilmSubComponentsFilmDrawerContent: typeof import("../components/FilmSubComponents/FilmDrawerContent.vue")['default']
export const LazyFormsAssessmentForm: typeof import("../components/Forms/AssessmentForm.vue")['default']
export const LazyFormsFilmForm: typeof import("../components/Forms/FilmForm.vue")['default']
export const LazyFormsPersonForm: typeof import("../components/Forms/PersonForm.vue")['default']
export const LazyFormsUserForm: typeof import("../components/Forms/UserForm.vue")['default']
export const LazyGalleryFilmGalleryEdit: typeof import("../components/Gallery/FilmGalleryEdit.vue")['default']
export const LazyGalleryFullscreenViewer: typeof import("../components/Gallery/GalleryFullscreenViewer.vue")['default']
export const LazyGalleryUploader: typeof import("../components/Gallery/GalleryUploader.vue")['default']
export const LazyGalleryViewer: typeof import("../components/Gallery/GalleryViewer.vue")['default']
export const LazyGalleryPartialsMultipleImgSelector: typeof import("../components/Gallery/Partials/MultipleImgSelector.vue")['default']
export const LazyGalleryPartialsSingleImgSelector: typeof import("../components/Gallery/Partials/SingleImgSelector.vue")['default']
export const LazyGalleryPersonGalleryEdit: typeof import("../components/Gallery/PersonGalleryEdit.vue")['default']
export const LazyMiscBaseError: typeof import("../components/Misc/BaseError.vue")['default']
export const LazyMiscCardLoader: typeof import("../components/Misc/CardLoader.vue")['default']
export const LazyMiscFileUploader: typeof import("../components/Misc/FileUploader.vue")['default']
export const LazyMiscFilters: typeof import("../components/Misc/Filters.vue")['default']
export const LazyMiscIndentedEditableText: typeof import("../components/Misc/IndentedEditableText.vue")['default']
export const LazyMiscListPage: typeof import("../components/Misc/ListPage.vue")['default']
export const LazyMiscLoadingScreen: typeof import("../components/Misc/LoadingScreen.vue")['default']
export const LazyMiscLogo: typeof import("../components/Misc/Logo.vue")['default']
export const LazyMiscNotAuthWarning: typeof import("../components/Misc/NotAuthWarning.vue")['default']
export const LazyMiscSearch: typeof import("../components/Misc/Search.vue")['default']
export const LazyMiscSuccessSnackbar: typeof import("../components/Misc/SuccessSnackbar.vue")['default']
export const LazyNavigationAppNavDrawerContent: typeof import("../components/Navigation/AppNavDrawerContent.vue")['default']
export const LazyNavigationProfileNav: typeof import("../components/Navigation/ProfileNav.vue")['default']
export const LazyAuthState: typeof import("../node_modules/.pnpm/nuxt-auth-utils@0.5.14_@simplewebauthn+browser@13.1.0_@simplewebauthn+server@13.1.1_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.9.0_db0@0.2.3_ioredis@5.5.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.2.0_@vue+compiler-dom@3.5.13_eslint@9.20.0_jiti@2.4.2__magicast@0.3.5_ro_6aead669bb20faf7755fc124e9998b85/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.1_@types+node@22.13.1_db0@0.2.3_eslint@9.20.0_jiti@2.4._e3babeaa2002b988fded74657d7ccb27/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
